# docker-compose.yml
version: '3.8'

services:
  # backtrader:
  #   build: .
  #   container_name: backtrader_container
  #   volumes:
  #     - .:/app
  #   command: python backtest.py

  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
