# docker-compose.yml
version: '3.8'

services:
  streamlit:
    build: docker/streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app

  jupyterlab:
    build: docker/jupyter
    volumes:
      - .:/app
    ports:
      - "8888:8888"